[package]
name = "rust_server"
version = "0.1.0"
authors = ["timglabisch <tim@ainfach.de>"]

[dependencies]
grpc = { git = "https://github.com/stepancheg/grpc-rust" }
protobuf = { git = "http://github.com/stepancheg/rust-protobuf" }
futures         = "0.1"
futures-cpupool = "0.1"
